# Generated by Django 6.1.1 on 2026-10-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_center_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Mobile', models.IntegerField()),
                ('Model', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Vehicle_no', models.TextField()),
                ('Problem', models.CharField()),
            ],
        ),
    ]
